### PR TITLE
Draft:Add kkmc

### PR DESCRIPTION
**Pull request by apricePhy**
Hi @dirkzerwas,

In this branch, I have added the first attempt at including KKMC. From my side the run-card looks ok but currently I cant test it in Key4hep (No access at the moment).

Could you see if the ".sh" at least runs KKMC and generates a LHEF?

### CODE REVIEW

**Comment by dirkzerwas** [comment]
Hi @Alan-Price,
I ran check.sh -r, but then went to Muon350_ISR.dat:
KKMCee -c Muon350_ISR.dat -o events.lhe
gives:
an events.lhe file (so the -o works, but it's empty (size 0)
In the execution step there is a line at the end:
KKee2f::InitParams: No final state fermions were selected.

If I add:
ln -sf Muon350_ISR.dat pro.input
and run again it works, or (keeping the link) 
KKMCee -o events.lhe works then too

--> -c seems to have a problem with the KEY4HEP version, We can bypass it by adding the link in the sh before execution.

--> The events.lhe output looks ok, (final state muons), but it would be kind of nice of the cross sections were written out as well? (I will make the same request to Carlo.... :)

--> There are also errors (I missed them first because the output is very verbose):

Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKdbase.h
   requested to autoload type KKdbase
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKdizet.h
   requested to autoload type KKdizet
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKborn.h
   requested to autoload type KKborn
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKevent.h
   requested to autoload type KKevent
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKarLud.h
   requested to autoload type KKarLud
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKpart.h
   requested to autoload type KKpart
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKbvir.h
   requested to autoload type KKbvir
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKarFin.h
   requested to autoload type KKarFin
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKqed3.h
   requested to autoload type KKqed3
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKceex.h
   requested to autoload type KKcmplx4
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKceex.h
   requested to autoload type KKcmplx2
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKceex.h
   requested to autoload type KKceex
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TauPair.h
   requested to autoload type TauPair
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for HepFace.h
   requested to autoload type HepFace
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for KKlasa.h
   requested to autoload type KKlasa

Cheers,
Dirk

**Comment by apricePhy** [comment]
Hi @dirkzerwas,

Regarding the "-c" option in key4hep, should we open an issue?

Regarding the cross-section, I have added HepMC3 to the current development branch of KKMC
which hopefully will be released soon. It will have the xs in hepmc and I will try to add it to the LHEF info.

For the KKMC error messages, I have not seen those before but I asked the authors.

Cheers,
Alan

**Comment by dirkzerwas** [comment]
Hi @apricePhy,

I checked the nightlies of March (probably the same as now):
kkmcee/5.00.02-sbe5kq/
is 5.00.02 the current production release or is it older? 
If it is older, we could ask for a first upgrade to see whether this makes the two problems go away?

**Comment by apricePhy** [comment]
Hi,

5.00.02 is the current release.

On 26. Apr 2024, at 14:41, Dirk Zerwas ***@***.***> wrote:



UWAGA: Wiadomość pochodzi od zewnętrznego nadawcy.




Hi @apricePhy<https://github.com/apricePhy>,

I checked the nightlies of March (probably the same as now):
kkmcee/5.00.02-sbe5kq/
is 5.00.02 the current production release or is it older?
If it is older, we could ask for a first upgrade to see whether this makes the two problems go away?

**Comment by apricePhy** [comment]
Hi @dirkzerwas,

The authors say the error messages are due to 
"It seems someone wants to use this class without loading the shared library which provides it.
See: cd /your/KKMCee-dev ; ls -al $(find . -name "rootlogon.C")"
Not sure what the solution is

Alan

**Comment by dirkzerwas** [comment]
Hi, 
on the input file problem: attached is the KKMC wrapper which calls KKMCee.exe installed on LCG:
[KKMCee.txt](https://github.com/key4hep/k4GeneratorsConfig/files/15137927/KKMCee.txt)
on -c or --config Argument $2 is written to _CONFFILE
later there is an existence test:

# Run existing config file
if test "x$_CONFFILE" = "x" || test ! -f $_CONFFILE; then
# We create a config file based on the input switches: this is the initial common part
cat > ./pro.input <<EOF

-> so if it fails, it will create pro.input from the command line input
-> there is no further use CONFFILE

Is the wrapper provided by KKMC or is it a KEY4HEP product? 

IMHO I think these lines in the wrapper:
----------------------------------------------------------------------------------
# Input file closing
cat >> ./pro.input <<EOF
********************************************************************************
EndX
EOF
fi
-----------------------------------------------------------------------------------
should be replaced by:
-----------------------------------------------------------------------------------
# Input file closing
cat >> ./pro.input <<EOF
********************************************************************************
EndX
EOF
else
ln -sf $_CONFFILE ./pro.input
fi
------------------------------------------------------------------------------------
since the if test the non-existence of the file, so in "else" we should be assured that $_CONFFILE exists, right?

Could you open an issue, I think I can't?

Cheers,
Dirk

**Pull request merged**
