### PR TITLE
Inheritance

### PR DESCRIPTION
**Pull request by dirkzerwas**
BEGINRELEASENOTES
- Introduction of Inheritance for the Generators
- Each Generator inherits from GeneratorBase
- GeneratorBase takes care of the configuration of the ouputfiles (paths/names)
- GeneratorBase provides the KEY4HEP setup
-  some renaming to make use less variables (but with longer names), eg the data cards are self,GeneratorDatacard etc
- removed "Run_" from the datacard name for simplicity

ENDRELEASENOTES

### CODE REVIEW

**Comment by dirkzerwas** [comment]
Added some bugfixes:
- removed the evx option
- the "outputformat" was never decoded and always fell on hepmc (which is ok) due to a typo ["ouputformat"] instead of ["outputformat"] (missing "t")

A general question should hepmc or hepmc3 be the default?

**Comment by apricePhy** [comment]
I would say hepmc3, it is more the 5 years old now and the default for many. I think its somewhat backwards compatible anyway

On 12. Apr 2024, at 09:35, Dirk Zerwas ***@***.***> wrote:



Added some bugfixes:

  *   removed the evx option
  *   the "outputformat" was never decoded and always fell on hepmc (which is ok) due to a typo ["ouputformat"] instead of ["outputformat"] (missing "t")

A general question should hepmc or hepmc3 be the default?

**Comment by dirkzerwas** [comment]
ok, I will move the default and modify the examples and references for hepmc3 in this branch

**Comment by dirkzerwas** [comment]
Hi @apricePhy,
is there a difference internally between EVENT_OUTPUT HepMC_GenEvent(name) and HepMC3_GenEvent(name)?
For HepMC2 : sherpa outputs:
name.hepmc2g
for HepMC3:
name
(cured by adding ".hepmc3g" to the argument of Hep, seems to work (CI running)

**Comment by apricePhy** [comment]
This is a common sherpa argument as to wether we should provide the ext
or the user. One camp did hepmc2 and the other hepmc3

I will ask that we at least be consistent between hepmc2/3 and port the correction.

On 12. Apr 2024, at 17:10, Dirk Zerwas ***@***.***> wrote:



Hi @apricePhy<https://github.com/apricePhy>,
is there a difference internally between EVENT_OUTPUT HepMC_GenEvent(name) and HepMC3_GenEvent(name)?
For HepMC2 : sherpa outputs:
name.hepmc2g
for HepMC3:
name
(cured by adding ".hepmc3g" to the argument of Hep, seems to work (CI running)

**Comment by dirkzerwas** [comment]
Great, switching to HepMC3 for sherpa we see the line:
WARNING::GenCrossSection::to_string: the number of cross-sections cross_sections.size()=1 does not match the number of weights5
but only once and not once per event (as for whizard) maybe the first write is affected?

**Comment by apricePhy** [comment]
Odd, in sherpa2 we dont have any physical additional “weights” but some process
info that hepmc sees as weights and requires an xs.
So we just set the nominal xs for each additional “Weight”.
Not sure there should be even one warning!

https://gitlab.com/sherpa-team/sherpa/-/merge_requests/742

On 12. Apr 2024, at 17:36, Dirk Zerwas ***@***.***> wrote:



Great, switching to HepMC3 for sherpa we see the line:
WARNING::GenCrossSection::to_string: the number of cross-sections cross_sections.size()=1 does not match the number of weights5
but only once and not once per event (as for whizard) maybe the first write is affected?

**Pull request merged**
